export const Prizes = [
    {
        id: 1,
        shoeTitle: "Travis Scott X Air Max 1 'Saturn Gold'",
        shoePrizeImages: [
        "https://i.ibb.co/7Km5KW0/Saturn-Gold-1.jpg",
        "https://i.ibb.co/30X4Ffp/Saturn-Gold-2.jpg",
        "https://i.ibb.co/m5b6V5W/Saturn-Gold-3.jpg",
        "https://i.ibb.co/3s5XwNZ/Saturn-Gold-4.jpg"],
        enteredTickets: 1955,
        prizeTotal: 4405,
        poolType: 'Normal',
        numberOfPairs: 6,
        ticketPrizes: {
            first: { amount: 100, places: 4 },
            second: { amount: 45, places: 15 },
            third: { amount: 25, places: 20 },
            fourth: { amount: 7, places: 30 }
        }
    },
    {
        id: 2,
        shoeTitle: "Kyrie 5 'Neon Sole'",
        shoePrizeImages: [
        "https://i.ibb.co/By3chKr/Kyrie-5-1.jpg",
        "https://i.ibb.co/P4bh49L/Kyrie-5-2.jpg",
        "https://i.ibb.co/5hS5gMp/Kyrie-5-3.jpg",
        "https://i.ibb.co/ZW2RhXW/Kyrie-5-4.jpg"],
        enteredTickets: 1807,
        prizeTotal: 4995,
        poolType: 'Normal',
        numberOfPairs: 7,
        ticketPrizes: {
            first: { amount: 110, places: 4 },
            second: { amount: 55, places: 14 },
            third: { amount: 25, places: 21 },
            fourth: { amount: 10, places: 26 }
        }
    },
    {
        id: 3,
        shoeTitle: "Zoom Kobe Proto 'Grinch'",
        shoePrizeImages: [
        "https://i.ibb.co/r4vrTT9/Kobe-6-1.jpg",
        "https://i.ibb.co/mcSJDnZ/Kobe-6-2.jpg",
        "https://i.ibb.co/cxpjWCT/Kobe-6-3.jpg",
        "https://i.ibb.co/3yBz9gj/Kobe-6-4.jpg"],
        enteredTickets: 807,
        prizeTotal: 6235,
        poolType: 'Normal',
        numberOfPairs: 4,
        ticketPrizes: {
            first: { amount: 150, places: 3 },
            second: { amount: 90, places: 10 },
            third: { amount: 50, places: 17 },
            fourth: { amount: 10, places: 30 }
        }
    },
    {
        id: 4,
        shoeTitle: "Off-White X Air Jordan 1 Retro High OG 'White' 2018",
        shoePrizeImages: [
        "https://i.ibb.co/X4z6bD7/Off-White-OG-White-1.jpg",
        "https://i.ibb.co/sPtYX24/Off-White-OG-White-2.jpg",
        "https://i.ibb.co/02QqWsS/Off-White-OG-White-3.jpg",
        "https://i.ibb.co/TYzpmGN/Off-White-OG-White-4.jpg",
        "https://i.ibb.co/LSLMSW4/Off-White-OG-White-5.jpg"],
        enteredTickets: 1884,
        prizeTotal: 14555,
        poolType: 'Rare',
        numberOfPairs: 2,
        ticketPrizes: {
            first: { amount: 450, places: 2 },
            second: { amount: 175, places: 10 },
            third: { amount: 75, places: 20 },
            fourth: { amount: 20, places: 30 }
        }
    },
    {
        id: 5,
        shoeTitle: "Yeezy Boost 350 V2 'Israfil'",
        shoePrizeImages: [
        "https://i.ibb.co/80syJQZ/yeezy-israfil-1.jpg",
        "https://i.ibb.co/yQswhkV/yeezy-israfil-2.jpg",
        "https://i.ibb.co/K2rRMTh/yeezy-israfil-3.jpg",
        "https://i.ibb.co/k5cR0p8/yeezy-israfil-4.jpg"],
        enteredTickets: 5101,
        prizeTotal: 6635,
        poolType: 'Normal',
        numberOfPairs: 7,
        ticketPrizes: {
            first: { amount: 150, places: 3 },
            second: { amount: 100, places: 10 },
            third: { amount: 40, places: 15 },
            fourth: { amount: 5, places: 35 }
        }
    },
    {
        id: 6,
        shoeTitle: "Air Jordan 9 Retro 'Chile Red'",
        shoePrizeImages: [
        "https://i.ibb.co/bPPMrLr/Chile-Red-1.jpg",
        "https://i.ibb.co/qJKxKyR/Chile-Red-2.jpg",
        "https://i.ibb.co/1Zqf3Zt/Chile-Red-3.jpg",
        "https://i.ibb.co/MkDXH5S/Chile-Red-4.jpg"],
        enteredTickets: 4222,
        prizeTotal: 5135,
        poolType: 'Normal',
        numberOfPairs: 6,
        ticketPrizes: {
            first: { amount: 95, places: 4 },
            second: { amount: 45, places: 12 },
            third: { amount: 20, places: 30 },
            fourth: { amount: 5, places: 35 }
        }
    }    
]

export const Shoes = [
    {
    id: 7,
    title: "Jordan 6 Retro 'Georgetown'",
    brand: 'Jordan',
    ticketPrices: [231, 227, 221, 219],
    images: [
    "https://i.ibb.co/2KpCsjN/Jordan-6-retro-1.jpg",
    "https://i.ibb.co/B2qWp75/Jordan-6-retro-2.jpg",
    "https://i.ibb.co/VNgTBbT/Jordan-6-retro-3.jpg",
    "https://i.ibb.co/g79yTPH/Jordan-6-retro-4.jpg"],
    specs: "",
    description: "Michael Jordan and the North Carolina Tar Heels faced off against the Georgetown Hoyas during the 1982 NCAA Tournament, where MJ hit the go ahead basket to cement a win in the final game. This Air Jordan 6 Retro utilizes signature Hoya colors across the retro hoops shoe, commemorating the epic finish. A grey suede upper showcases perforated detailing and a Huarache inner sleeve for a custom fit. Navy accents add a nice pop of contrast on the heel tab, Jumpman logo and the midsole. A visible NIke Air unit gives way to a translucent outsole, finishing the look.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 8,
    title: "Air Max 720 Metallic Platinum",
    brand: 'Nike',
    ticketPrices: [128, 124, 122, 118],
    images: [
    "https://i.ibb.co/D1x4BZT/Air-Max-720-Metallic-Platinum-1.jpg",
    "https://i.ibb.co/kqKtNvz/Air-Max-720-Metallic-Platinum-2.jpg",                
    "https://i.ibb.co/ZzYtVVx/Air-Max-720-Metallic-Platinum-3.jpg",
    "https://i.ibb.co/zGLnMwz/Air-Max-720-Metallic-Platinum-4.jpg"],
    specs: "",
    description: "The Air Max 720 'Metallic Platinum' features a simple colorway on its performance design. The shoe's textile upper features sculpted design lines, with TPU overlays on the quarter panel and heel for support. A heel pull-loop is included for easy on and off, while underfoot, the translucent full-length 720 Max Air unit provides cushining.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 9,
    title: "YEEZY BOOST 350 V2 'SLATE'",
    brand: 'Adidas',
    ticketPrices: [241, 237, 235, 230],
    images: [
    "https://i.ibb.co/x2hXPfW/Yeezy-Boost-350-V2-Slate-1.jpg",
    "https://i.ibb.co/gj9j2HK/Yeezy-Boost-350-V2-Slate-2.jpg",
    "https://i.ibb.co/w6jm69c/Yeezy-Boost-350-V2-Slate-3.jpg",
    "https://i.ibb.co/vzGfPLq/Yeezy-Boost-350-V2-Slate-4.jpg"],
    specs: "",
    description: "The adidas Yeezy Boost 350 V2 'Slate' features a two-tone color block, featuring a light tan hue across the Primeknit upper, intersected by a black stripe across the middle with 'SPLY-350' branding. Full-length Boost cushioning is embedded in the beige TPU translucent midsole, while a gum rubber outsole features a unique traction pattern for grip.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 10,
    title: "Off-White X Air Jordan 5 SP 'Sail'",
    brand: 'Jordan',
    ticketPrices: [455, 450, 447, 440],
    images: [
    "https://i.ibb.co/y6zXJ7g/Off-white-jordan-sail-1.jpg",
    "https://i.ibb.co/0rhywF4/Off-white-jordan-sail-2.jpg",
    "https://i.ibb.co/gD9hCKm/Off-white-jordan-sail-3.jpg",
    "https://i.ibb.co/jvfBs9j/Off-white-jordan-sail-4.jpg"],
    specs: "",
    description: "Jordan Brand teamed up with Virgil Abloh's luxury streetwear label to create the Off-White x Air Jordan 5 Retro 'Fire Red' in October 2020. A follow-up to an early 2020 Air Jordan 5 collaboration, the shoe's upper features an off-white textile construction, with the midfoot, collar and reflective silver tongue sporting circular cutouts. Helvetica text marks the medial side, while underfoot, a contrasting black midsole houses Air in the heel for cushioning. A pre-yellowed finish on the outsole, which provides traction, completes the look.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 12,
    title: "Air Jordan 11 Retro 'Cherry'",
    brand: 'Jordan',
    ticketPrices: [555, 549, 546, 540],
    images: [
    "https://i.ibb.co/G7y6RsH/Jordan-11-Cherry-1.jpg",
    "https://i.ibb.co/bHKtj4M/Jordan-11-Cherry-2.jpg",
    "https://i.ibb.co/kcG9HBq/Jordan-11-Cherry-3.jpg",
    "https://i.ibb.co/ZWfVRvq/Jordan-11-Cherry-4.jpg"],
    specs: "",
    description: "A new entry in the lineage of the Air Jordan 11, the 'Cherry' features a clean colorway that utilizes a Chicago Bulls inspired palette. The upper features white mesh with tonal webbing eyelets, while a shiny patent leather mudguard wraps around the entire shoe in a deep red hue. A red Jumpman logo appears on the back heel area, while a translucent rubber outsole finishes the look. A lightweight Phylon midsole provides cushioning while a carbon fiber spring plate offers structural support underfoot.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 13,
    title: "Beams X Paperboy Paris X 920 Made In England 'Ice Boy'",
    brand: 'New Balance',
    ticketPrices: [305, 300, 297, 292],
    images: [
    "https://i.ibb.co/yBPqHLH/Beams-x-paperboy-1.jpg",
    "https://i.ibb.co/d6L43m3/Beams-x-paperboy-2.jpg",
    "https://i.ibb.co/Qp5yhtJ/Beams-x-paperboy-3.jpg",
    "https://i.ibb.co/wJdHLd4/Beams-x-paperboy-4.jpg",
    "https://i.ibb.co/5W7Bhg9/Beams-x-paperboy-5.jpg"],
    specs: ["Mesh Upper", "Suede Overlays", "ENCAP Midsole", "Embroidered Branding", "Rubber Outsole", "Made in UK"],
    description: "New Balance are known for their high quality collabs and this one is no exception. Combining with Beams and Paperboy we are treated to a sleek 920, featuring mesh uppers with grey suede overlays, ENCAP midsole and finished with embroidered branding on the tongue.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 14,
    title: "Rick And Morty X MB.01",
    brand: 'Puma',
    ticketPrices: [295, 292, 297, 296],
    images: [
    "https://i.ibb.co/2dfhtRz/Rick-and-morty-1.jpg",
    "https://i.ibb.co/k4qPw47/Rick-and-morty-2.jpg",
    "https://i.ibb.co/3yNpFqQ/Rick-and-morty-3.jpg",
    "https://i.ibb.co/TcdCCmx/Rick-and-morty-4.jpg",
    "https://i.ibb.co/P9WJ45v/Rick-and-morty-5.jpg",
    "https://i.ibb.co/chwtWJ3/Rick-and-morty-6.jpg",
    "https://i.ibb.co/80dR2kd/Rick-and-morty-7.jpg",
    "https://i.ibb.co/kBw35qV/Rick-and-morty-8.jpg"],
    specs: ["Green/Red", "Logo print to the side", "Round Toe", "Front lace-up fastening", "Branded insole", "Rubber sole"],
    description: "Paying tribute to Lamelo Ball's favorite show on Adult Swim, the Rick and Morty x PUMA MB.01 showcases a mismatched design that pairs a neon green finish on the left shoe with a vibrant crimson finish on the right. Rick and Morty branding is featured on the mesh upper on the toe box, along with graphics on the lace guard. It's built on a full-length Nitro Foam midsole.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 15,
    title: "Curry 2 'All Star'",
    brand: 'Under Armour',
    ticketPrices: [341, 338, 335, 330],
    images: [
    "https://i.ibb.co/fNfWf9F/Curry-2-1.jpg",
    "https://i.ibb.co/k3MK8qM/Curry-2-2.jpg",
    "https://i.ibb.co/5x9ZMmh/Curry-2-3.jpg",
    "https://i.ibb.co/5LGSn6Q/Curry-2-4.jpg"],
    specs: ["Green/Red", "Logo print to the side", "Round Toe", "Front lace-up fastening", "Branded insole", "Rubber sole"],
    description: "Under Armour pays tribute to Stephen Curry with the Curry 2 'All Star', the sneaker he wore at the 2016 NBA All-Star Game. Released in February 2016, the shoe features a white SpeedForm upper with a red inner lining and metallic gold Under Armour branding and hardware. It also boasts a white external heel counter, a full-length white Charged Cushioning midsole, and a gold-speckled, icy translucent herringbone rubber outsole.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 16,
    title: "Kawhi 2 'New Money'",
    brand: 'New Balance',
    ticketPrices: [166, 163, 160, 157],
    images: [
    "https://i.ibb.co/7ktbgd7/Kawhi-2-1.jpg",
    "https://i.ibb.co/2sJZdGx/Kawhi-2-2.jpg",
    "https://i.ibb.co/QcHXxFw/Kawhi-2-3.jpg",
    "https://i.ibb.co/6XKm5rk/Kawhi-2-4.jpg"],
    specs: ["FitWeave Lite upper holds the shape, offering a long-lasting and locked-in fit", "Propulsive FuelCell midsole delivers an excellent rebound feel in every step"],
    description: "An on-court monster designed for the everyday grind, the New Balance Kawhi II lets your grade-schoolers score the perfect slam dunk each time. The outsole, midsole, and upper are inspired by Kawhis massive hands, taking hold of the game — give your boys the OG hardwood feel in every step. Designed to provide the best on and off the court, the New Balance Kawhi II guarantees built-in energy return and stability for enhanced performance.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 17,
    title: "Air Jordan 3 Retro 'Fire Red' 2022",
    brand: 'Jordan',
    ticketPrices: [215, 210, 206, 199],
    images: [
    "https://i.ibb.co/By7sMwV/Jordan-3-1.jpg",
    "https://i.ibb.co/YkPdn80/Jordan-3-2.jpg",
    "https://i.ibb.co/wJxNXmX/Jordan-3-3.jpg",
    "https://i.ibb.co/4N2x16X/Jordan-3-4.jpg"],
    specs: ["Tumbled Leather Upper", "Elephant Print Detailing", "Visible Air-Sole Unit", "Solid Rubber Outsole"],
    description: "The Air Jordan 3 Retro 'Fire Red' sees one of the original colors of the silhouette return, true to form. A white leather upper is paired with grey elephant print overlays on the toe and heel, while Fire Red accents on the midsole and collor offers a pop of contrast. Designed by Tinker Hatfield, the Air Jordan 3 was the first to feature a visible Nike Air unit, along with the Jumpman logo. This 2022 edition sees the return of the 'Nike Air' logo on the back heel, along with the 'Nike' wordmark on the outsole.",
    availableSizes: [
        {5: 2}, 
        {5.5: 0},
        {6: 0},
        {6.5: 1},
        {7: 2},
        {7.5: 3},
        {8: 1},
        {8.5: 3},
        {9: 2}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 2},
        {12: 2},
        {12.5: 2},
        {13: 2}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 1},
        {17: 1}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 18,
    title: "Air Jordan 7 Retro 'Ray Allen' PE",
    brand: 'Jordan',
    ticketPrices: [371, 367, 364, 355],
    images: [
    "https://i.ibb.co/QCRQ6dZ/Jordan-7-Ray-Allen-1.jpg",
    "https://i.ibb.co/nPtqYzk/Jordan-7-Ray-Allen-2.jpg",
    "https://i.ibb.co/zFwtJRc/Jordan-7-Ray-Allen-3.jpg",
    "https://i.ibb.co/YcpqmYb/Jordan-7-Ray-Allen-4.jpg"],
    specs: ["Neoprene outer", "Logo patch at the tongue", "Rubber Sole", "Pull tab heel"],
    description: "Also known as the 'Bucks Away,' the Air Jordan 7 Retro 'Ray Allen' PE gives the nod to the first NBA team that Ray Allen played for. Appearing in the Milwaukee Bucks' throwback colors, the shoe's black nubuck upper is accented by Fierce Purple and Dark Grey Steel on the midsole detailing, outsole, tongue and branding.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 0},
        {7.5: 3},
        {8: 1},
        {8.5: 1},
        {9: 0}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 0},
        {12: 1},
        {12.5: 2},
        {13: 0}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 0},
        {17: 0}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 19,
    title: "Air Jordan 1 Retro High '85 OG 'Neutral Grey'",
    brand: 'Jordan',
    ticketPrices: [313, 310, 307, 302],
    images: [
    "https://i.ibb.co/3T290Rn/Jordan-1-Neutral-Grey-1.jpg",
    "https://i.ibb.co/0yMJNLZ/Jordan-1-Neutral-Grey-2.jpg",
    "https://i.ibb.co/2S6wfZW/Jordan-1-Neutral-Grey-3.jpg",
    "https://i.ibb.co/0yNVTFB/Jordan-1-Neutral-Grey-4.jpg"],
    specs: ["Rubber Sole", "Leather Outer", "Fabric Lining", "Signature Swoosh logo detail"],
    description: "Released in February 2021, the Air Jordan 1 Retro High '85 OG 'Neutral Grey' is the first reissue of an OG colorway. The shoe's leather upper appears primarily in white, complemented by Neutral Grey suede on the Swoosh and collar. Classic branding hits on the tongue tag, sockliner and 'Wings' logo add to the aesthetic, while underfoot, the midsole houses the usual concealed Air in the heel for cushioning. More Neutral Grey on the concentric outsole completes the look.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 0},
        {7.5: 3},
        {8: 1},
        {8.5: 1},
        {9: 0}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 0},
        {12: 1},
        {12.5: 2},
        {13: 0}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 0},
        {17: 0}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 20,
    title: "Yeezy Boost 700 'Mauve",
    brand: 'Adidas',
    ticketPrices: [366, 360, 357, 354],
    images: [
    "https://i.ibb.co/1MgDW9z/Yeezy-Mauve-1.jpg",
    "https://i.ibb.co/nMXmwRQ/Yeezy-Mauve-2.jpg",
    "https://i.ibb.co/Dz9WnrW/Yeezy-Mauve-3.jpg",
    "https://i.ibb.co/5rJZnTT/Yeezy-Mauve-4.jpg"],
    specs: ["Leather/Fabric Outer", "Rubber Sole", "Fabric Lining", "Contrasting panel detail"],
    description: "The somber color scheme of the Yeezy Boost 700 'Mauve'blends black and purplish grey across its signature multi-layered upper. The complex arrangement showcases different varieties of mesh complemented with suede and textured leather paneling, all rising above a tonal sculpted midsole brightened with pops of neon green. Exterior branding is limited to understated Three-Stripes on the quarter panel and an adidas logo embossed on the outsole.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 0},
        {7.5: 3},
        {8: 1},
        {8.5: 1},
        {9: 0}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 0},
        {12: 1},
        {12.5: 2},
        {13: 0}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 0},
        {17: 0}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 21,
    title: "Xbox 360 X Forum Mid '20TH Anniversary",
    brand: 'Adidas',
    ticketPrices: [197, 196, 191, 188],
    images: [
    "https://i.ibb.co/kmkSb0g/Forum-xbox-1.jpg",
    "https://i.ibb.co/F7tVhMC/Forum-xbox-2.jpg",
    "https://i.ibb.co/x3KXZNC/Forum-xbox-3.jpg",
    "https://i.ibb.co/RgkbX9j/Forum-xbox-4.jpg"],
    specs: ["Leather Outer", "Rubber Sole", "Fabric Lining", "Front toush-strap fastening", "Side stripe detailing"],
    description: "Celebrating two decades of Microsoft's gaming console is the Xbox 360 x adidas Forum Mid '20th Anniversary.' The limited colorway is inspired by the design of the original Xbox 360 console, highlighted by a white leather upper with dark grey accents and a metallic silver Xbox button on the lateral ankle. An adjustable ankle strap features detailing that nods to the Xbox 360 disc tray, with heel overlay references the removable hard drive and memory unit slots.",
    availableSizes: [
        {5: 2}, 
        {5.5: 1},
        {6: 2},
        {6.5: 1},
        {7: 0},
        {7.5: 3},
        {8: 1},
        {8.5: 1},
        {9: 0}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 0},
        {12: 1},
        {12.5: 2},
        {13: 0}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 0},
        {17: 0}, 
        {17.5: 0},
        {18: 1}
    ]},
    {
    id: 22,
    title: "Off-White X Chuck 70 'White'",
    brand: 'Converse',
    ticketPrices: [350, 341, 337, 329],
    images: [
    "https://i.ibb.co/wsbwRxq/Off-White-Converse-1.jpg",
    "https://i.ibb.co/mSXJH3z/Off-White-Converse-2.jpg",
    "https://i.ibb.co/tQCvtmc/Off-White-Converse-3.jpg",
    "https://i.ibb.co/Xt1dWLK/Off-White-Converse-4.jpg"],
    specs: ["Cotton Outer", "Rubber Sole", "Fabric Lining"],
    description: "Virgil Abloh emphasizes accessibility and wearability with the OFF-WHITE x Chuck 70 'White' collab. As a result, the classic silhouette is ensconced in traditional cotton canvas and finished in a versatile crisp white shade. Virgil retains the shoe's signature and rubber license plate, though the latter is turned upside down. Additional flourishes include the OFF-WHITE's trademark diagonal midsole stripes, printed text on the medial side, and a bright orange outsole.",
    availableSizes: [
        {5: 2}, 
        {5.5: 0},
        {6: 1},
        {6.5: 2},
        {7: 0},
        {7.5: 0},
        {8: 1},
        {8.5: 1},
        {9: 0}, 
        {9.5: 4},
        {10: 3},
        {10.5: 1},
        {11: 2},
        {11.5: 0},
        {12: 1},
        {12.5: 1},
        {13: 1}, 
        {13.5: 0},
        {14: 1},
        {14.5: 0},
        {15: 1},
        {15.5: 0},
        {16: 0},
        {16.5: 0},
        {17: 0}, 
        {17.5: 0},
        {18: 0}
    ]}
]